version_info: "0"
resources:
- '@type': type.googleapis.com/envoy.api.v2.ClusterLoadAssignment
  cluster_name: "GrpcService"
  endpoints:
  - lb_endpoints:
    - endpoint:
        address:
          socket_address:
            address: 127.0.0.1 
            port_value: "8181" 