version_info: "0"
resources:
- '@type': type.googleapis.com/envoy.api.v2.RouteConfiguration
  name: local_route 
  virtual_hosts:
  - name: "GrpcService"
    domains:
    - "localhost"
    routes:
    - match:
        prefix: /
      route:
        cluster: "GrpcService" 
        timeout: 60s