version: '3.7'
services:
  envoy:
    container_name: envoy
    build:
      context: ./envoy-proxy
      dockerfile: Dockerfile
    ports: 
      - 9901:9901
      - 5501:5501
    expose: 
      - "8181"